import { AppContent } from "@/components";
import { Analytics } from "@vercel/analytics/react";

import "./globals.scss";

export const metadata = {
  title: "Fullstack Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="pt-br">
      <body>
        <AppContent session={session}>{children}</AppContent>
        <Analytics />
      </body>
    </html>
  );
}
