import { NavbarTopo } from "@/components";

export const metadata = {
  title: "Fullstack Blog",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <div className="container">
      <div className="col-11 col-md-8 mx-auto">
        <NavbarTopo></NavbarTopo>

        {children}

        <footer className="pt-4 my-md-5 pt-md-5 border-top">
          <div className="row">
            <div className="col-12 col-md">
              <div className="fw-bold">Fullstack Blog</div>
              <small className="d-block mb-3 text-body-secondary">
                &copy; 2023
              </small>
            </div>
            <div className="col-6 col-md">
              <h5>Sobre</h5>
              <ul className="list-unstyled text-small">
                <li className="mb-1">
                  <a className="link-secondary text-decoration-none" href="#">
                    Sobre o blog
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}
